// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// csqrt
NumericVector csqrt(NumericVector x);
RcppExport SEXP _gamrel_csqrt(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(csqrt(x));
    return rcpp_result_gen;
END_RCPP
}
// order1_c
IntegerVector order1_c(NumericVector x);
RcppExport SEXP _gamrel_order1_c(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(order1_c(x));
    return rcpp_result_gen;
END_RCPP
}
// mean_c
double mean_c(NumericVector x);
RcppExport SEXP _gamrel_mean_c(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(mean_c(x));
    return rcpp_result_gen;
END_RCPP
}
// lambda_func_ifr_c
NumericVector lambda_func_ifr_c(NumericVector tvec, NumericVector thetavec, NumericVector wvec, double lambda0);
RcppExport SEXP _gamrel_lambda_func_ifr_c(SEXP tvecSEXP, SEXP thetavecSEXP, SEXP wvecSEXP, SEXP lambda0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type tvec(tvecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type thetavec(thetavecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type wvec(wvecSEXP);
    Rcpp::traits::input_parameter< double >::type lambda0(lambda0SEXP);
    rcpp_result_gen = Rcpp::wrap(lambda_func_ifr_c(tvec, thetavec, wvec, lambda0));
    return rcpp_result_gen;
END_RCPP
}
// lambda_func_dfr_c
NumericVector lambda_func_dfr_c(NumericVector tvec, NumericVector thetavec, NumericVector wvec, double lambda0);
RcppExport SEXP _gamrel_lambda_func_dfr_c(SEXP tvecSEXP, SEXP thetavecSEXP, SEXP wvecSEXP, SEXP lambda0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type tvec(tvecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type thetavec(thetavecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type wvec(wvecSEXP);
    Rcpp::traits::input_parameter< double >::type lambda0(lambda0SEXP);
    rcpp_result_gen = Rcpp::wrap(lambda_func_dfr_c(tvec, thetavec, wvec, lambda0));
    return rcpp_result_gen;
END_RCPP
}
// lambda_func_lwb_c
NumericVector lambda_func_lwb_c(NumericVector tvec, NumericVector thetavec, NumericVector wvec, double a);
RcppExport SEXP _gamrel_lambda_func_lwb_c(SEXP tvecSEXP, SEXP thetavecSEXP, SEXP wvecSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type tvec(tvecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type thetavec(thetavecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type wvec(wvecSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(lambda_func_lwb_c(tvec, thetavec, wvec, a));
    return rcpp_result_gen;
END_RCPP
}
// int_lambda_func_ifr_c
NumericVector int_lambda_func_ifr_c(NumericVector tvec, NumericVector thetavec, NumericVector wvec, double lambda0);
RcppExport SEXP _gamrel_int_lambda_func_ifr_c(SEXP tvecSEXP, SEXP thetavecSEXP, SEXP wvecSEXP, SEXP lambda0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type tvec(tvecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type thetavec(thetavecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type wvec(wvecSEXP);
    Rcpp::traits::input_parameter< double >::type lambda0(lambda0SEXP);
    rcpp_result_gen = Rcpp::wrap(int_lambda_func_ifr_c(tvec, thetavec, wvec, lambda0));
    return rcpp_result_gen;
END_RCPP
}
// int_lambda_func_dfr_c
NumericVector int_lambda_func_dfr_c(NumericVector tvec, NumericVector thetavec, NumericVector wvec, double lambda0);
RcppExport SEXP _gamrel_int_lambda_func_dfr_c(SEXP tvecSEXP, SEXP thetavecSEXP, SEXP wvecSEXP, SEXP lambda0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type tvec(tvecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type thetavec(thetavecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type wvec(wvecSEXP);
    Rcpp::traits::input_parameter< double >::type lambda0(lambda0SEXP);
    rcpp_result_gen = Rcpp::wrap(int_lambda_func_dfr_c(tvec, thetavec, wvec, lambda0));
    return rcpp_result_gen;
END_RCPP
}
// int_lambda_func_lwb_c
NumericVector int_lambda_func_lwb_c(NumericVector tvec, NumericVector thetavec, NumericVector wvec, double a);
RcppExport SEXP _gamrel_int_lambda_func_lwb_c(SEXP tvecSEXP, SEXP thetavecSEXP, SEXP wvecSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type tvec(tvecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type thetavec(thetavecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type wvec(wvecSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(int_lambda_func_lwb_c(tvec, thetavec, wvec, a));
    return rcpp_result_gen;
END_RCPP
}
// int_lambda_func_lcv_c
NumericVector int_lambda_func_lcv_c(NumericVector tvec, NumericVector thetavec, NumericVector wvec, double lambda0, double w0);
RcppExport SEXP _gamrel_int_lambda_func_lcv_c(SEXP tvecSEXP, SEXP thetavecSEXP, SEXP wvecSEXP, SEXP lambda0SEXP, SEXP w0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type tvec(tvecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type thetavec(thetavecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type wvec(wvecSEXP);
    Rcpp::traits::input_parameter< double >::type lambda0(lambda0SEXP);
    Rcpp::traits::input_parameter< double >::type w0(w0SEXP);
    rcpp_result_gen = Rcpp::wrap(int_lambda_func_lcv_c(tvec, thetavec, wvec, lambda0, w0));
    return rcpp_result_gen;
END_RCPP
}
// shellSort_c
NumericVector shellSort_c(NumericVector x);
RcppExport SEXP _gamrel_shellSort_c(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(shellSort_c(x));
    return rcpp_result_gen;
END_RCPP
}
// order_c
IntegerVector order_c(NumericVector x);
RcppExport SEXP _gamrel_order_c(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(order_c(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _gamrel_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gamrel_csqrt", (DL_FUNC) &_gamrel_csqrt, 1},
    {"_gamrel_order1_c", (DL_FUNC) &_gamrel_order1_c, 1},
    {"_gamrel_mean_c", (DL_FUNC) &_gamrel_mean_c, 1},
    {"_gamrel_lambda_func_ifr_c", (DL_FUNC) &_gamrel_lambda_func_ifr_c, 4},
    {"_gamrel_lambda_func_dfr_c", (DL_FUNC) &_gamrel_lambda_func_dfr_c, 4},
    {"_gamrel_lambda_func_lwb_c", (DL_FUNC) &_gamrel_lambda_func_lwb_c, 4},
    {"_gamrel_int_lambda_func_ifr_c", (DL_FUNC) &_gamrel_int_lambda_func_ifr_c, 4},
    {"_gamrel_int_lambda_func_dfr_c", (DL_FUNC) &_gamrel_int_lambda_func_dfr_c, 4},
    {"_gamrel_int_lambda_func_lwb_c", (DL_FUNC) &_gamrel_int_lambda_func_lwb_c, 4},
    {"_gamrel_int_lambda_func_lcv_c", (DL_FUNC) &_gamrel_int_lambda_func_lcv_c, 5},
    {"_gamrel_shellSort_c", (DL_FUNC) &_gamrel_shellSort_c, 1},
    {"_gamrel_order_c", (DL_FUNC) &_gamrel_order_c, 1},
    {"_gamrel_rcpp_hello_world", (DL_FUNC) &_gamrel_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_gamrel(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
