# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Take the square root of a number
#'
#' @param x A number.
#' @return sqrt(x)
#' @export
csqrt <- function(x) {
    .Call(`_gamrel_csqrt`, x)
}

#' C version of order() - bad performance with duplicates
#' 
#' @export
orderfunc_c <- function(x) {
    .Call(`_gamrel_orderfunc_c`, x)
}

#' C version of mean()
#' 
#' @export
meanfunc_c <- function(x) {
    .Call(`_gamrel_meanfunc_c`, x)
}

#' Make DPP beta draws given a set of unscaled stick breaking weights
#' 
#' @export
makev_c <- function(uvec) {
    .Call(`_gamrel_makev_c`, uvec)
}

#' Hazard rate function - CON
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate
#' 
#' @description Hazard rate function for constant hazard
#' 
#' @export
hazf_con_c <- function(tvec, lambda0) {
    .Call(`_gamrel_hazf_con_c`, tvec, lambda0)
}

#' Integrated Hazard rate function - CON
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate
#' 
#' @description Integrated hazard rate function for constant hazard
#' 
#' @export
chzf_con_c <- function(tvec, lambda0) {
    .Call(`_gamrel_chzf_con_c`, tvec, lambda0)
}

#' Hazard and Integrated Hazard rate functions - CON
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate
#' 
#' @description Hazard rate and integrated hazard rate functions generated by 
#' a set of discrete locations and weights and integrated
#' 
#' @export
hazf_chzf_con_c <- function(tvec, lambda0) {
    .Call(`_gamrel_hazf_chzf_con_c`, tvec, lambda0)
}

#' Inverse survival function - CON
#' 
#' @param uvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate
#' 
#' @description Inverse survival function for constant hazard
#' 
#' @export
invsurvf_con_c <- function(uvec, lambda0) {
    .Call(`_gamrel_invsurvf_con_c`, uvec, lambda0)
}

#' Log prior - CON
#' 
#' 
#' @param lambda0 lambda0: constant hazard rate
#' @param nu exponential prior
#' 
#' @description log(prior) for the CON model - in vector form
#' 
#' @export
logprior_con_c <- function(lambda0, s1, s2) {
    .Call(`_gamrel_logprior_con_c`, lambda0, s1, s2)
}

#' Hazard rate function - IFR
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate
#' @param thetavec Locations
#' @param wvec Weights
#' 
#' @description Hazard rate function for IFR hazard
#' 
#' @export
hazf_ifr_c <- function(tvec, lambda0, thetavec, wvec) {
    .Call(`_gamrel_hazf_ifr_c`, tvec, lambda0, thetavec, wvec)
}

#' Integrated Hazard rate function - IFR
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate
#' @param thetavec Locations
#' @param wvec Weights
#' 
#' @description Integrated hazard rate function for IFR hazard
#' 
#' @export
chzf_ifr_c <- function(tvec, lambda0, thetavec, wvec) {
    .Call(`_gamrel_chzf_ifr_c`, tvec, lambda0, thetavec, wvec)
}

#' Hazard and Integrated Hazard rate functions - IFR
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate
#' @param thetavec Locations
#' @param wvec Weights
#' 
#' @description Hazard rate and integrated hazard rate functions generated by 
#' a set of discrete locations and weights and integrated
#' 
#' @export
hazf_chzf_ifr_c <- function(tvec, lambda0, thetavec, wvec) {
    .Call(`_gamrel_hazf_chzf_ifr_c`, tvec, lambda0, thetavec, wvec)
}

#' Log prior - IFR/DFR/CIR/CDR
#' 
#' 
#' @param eta eta
#' @param gamma gamma
#' 
#' @description log(prior) for the IFR, DFR, CIR and CDR models - in vector form
#' 
#' @export
logprior_ifr_c <- function(lambda0, gamma, thetavec, vvec, alpha, beta, nu, phi, s1, s2, a1, a2, b1, b2, g1, g2, f1, f2) {
    .Call(`_gamrel_logprior_ifr_c`, lambda0, gamma, thetavec, vvec, alpha, beta, nu, phi, s1, s2, a1, a2, b1, b2, g1, g2, f1, f2)
}

#' Hazard rate function - DFR
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate
#' @param thetavec Locations
#' @param wvec Weights
#' 
#' @description Hazard rate function for DFR hazard
#' 
#' @export
hazf_dfr_c <- function(tvec, lambda0, thetavec, wvec) {
    .Call(`_gamrel_hazf_dfr_c`, tvec, lambda0, thetavec, wvec)
}

#' Integrated Hazard rate function - DFR
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate
#' @param thetavec Locations
#' @param wvec Weights
#' 
#' @description Integrated hazard rate function for DFR hazard
#' 
#' @export
chzf_dfr_c <- function(tvec, lambda0, thetavec, wvec) {
    .Call(`_gamrel_chzf_dfr_c`, tvec, lambda0, thetavec, wvec)
}

#' Hazard and Integrated Hazard rate functions - DFR
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate
#' @param thetavec Locations
#' @param wvec Weights
#' 
#' @description Hazard rate and integrated hazard rate functions generated by 
#' a set of discrete locations and weights and integrated
#' 
#' @export
hazf_chzf_dfr_c <- function(tvec, lambda0, thetavec, wvec) {
    .Call(`_gamrel_hazf_chzf_dfr_c`, tvec, lambda0, thetavec, wvec)
}

#' Hazard rate function - CIR
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate
#' @param thetavec Locations
#' @param wvec Weights
#' 
#' @description Hazard rate function for CIR hazard
#' 
#' @export
hazf_cir_c <- function(tvec, lambda0, thetavec, wvec) {
    .Call(`_gamrel_hazf_cir_c`, tvec, lambda0, thetavec, wvec)
}

#' Integrated Hazard rate function - CIR
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate
#' @param thetavec Locations
#' @param wvec Weights
#' 
#' @description Integrated hazard rate function for CIR hazard
#' 
#' @export
chzf_cir_c <- function(tvec, lambda0, thetavec, wvec) {
    .Call(`_gamrel_chzf_cir_c`, tvec, lambda0, thetavec, wvec)
}

#' Hazard and Integrated Hazard rate functions - CIR
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate
#' @param thetavec Locations
#' @param wvec Weights
#' 
#' @description Hazard rate and integrated hazard rate functions generated by 
#' a set of discrete locations and weights and integrated
#' 
#' @export
hazf_chzf_cir_c <- function(tvec, lambda0, thetavec, wvec) {
    .Call(`_gamrel_hazf_chzf_cir_c`, tvec, lambda0, thetavec, wvec)
}

#' Hazard rate function - CDR
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate
#' @param thetavec Locations
#' @param wvec Weights
#' 
#' @description Hazard rate function for CDR hazard
#' 
#' @export
hazf_cdr_c <- function(tvec, lambda0, thetavec, wvec) {
    .Call(`_gamrel_hazf_cdr_c`, tvec, lambda0, thetavec, wvec)
}

#' Integrated Hazard rate function - CDR
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate
#' @param thetavec Locations
#' @param wvec Weights
#' 
#' @description Integrated hazard rate function for CIR hazard
#' 
#' @export
chzf_cdr_c <- function(tvec, lambda0, thetavec, wvec) {
    .Call(`_gamrel_chzf_cdr_c`, tvec, lambda0, thetavec, wvec)
}

#' Hazard and Integrated Hazard rate functions - CDR
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate
#' @param thetavec Locations
#' @param wvec Weights
#' 
#' @description Hazard rate and integrated hazard rate functions generated by 
#' a set of discrete locations and weights and integrated
#' 
#' @export
hazf_chzf_cdr_c <- function(tvec, lambda0, thetavec, wvec) {
    .Call(`_gamrel_hazf_chzf_cdr_c`, tvec, lambda0, thetavec, wvec)
}

#' Hazard rate function - LWB
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate
#' @param a Change point
#' @param thetavec Locations
#' @param wvec Weights
#' 
#' @description Hazard rate function for LWB hazard
#' 
#' @export
hazf_lwb_c <- function(tvec, lambda0, a, thetavec, wvec) {
    .Call(`_gamrel_hazf_lwb_c`, tvec, lambda0, a, thetavec, wvec)
}

#' Integrated Hazard rate function - LWB
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate
#' @param a Change point
#' @param thetavec Locations
#' @param wvec Weights
#' 
#' @description Integrated hazard rate function for LWB hazard
#' 
#' @export
chzf_lwb_c <- function(tvec, lambda0, a, thetavec, wvec) {
    .Call(`_gamrel_chzf_lwb_c`, tvec, lambda0, a, thetavec, wvec)
}

#' Hazard and Integrated Hazard rate functions - LWB
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate
#' @param a Change point
#' @param thetavec Locations
#' @param wvec Weights
#' 
#' @description Hazard rate and integrated hazard rate functions generated by 
#' a set of discrete locations and weights and integrated
#' 
#' @export
hazf_chzf_lwb_c <- function(tvec, lambda0, a, thetavec, wvec) {
    .Call(`_gamrel_hazf_chzf_lwb_c`, tvec, lambda0, a, thetavec, wvec)
}

#' Log prior - LWB/HBT/HCV
#' 
#' 
#' @param eta eta
#' @param gamma gamma
#' 
#' @description log(prior) for the LWB, HBT and HCV models - in vector form
#' 
#' @export
logprior_lwb_c <- function(lambda0, gamma, thetavec, vvec, a, alpha, beta, nu, phi, s1, s2, c1, c2, a1, a2, b1, b2, g1, g2, f1, f2) {
    .Call(`_gamrel_logprior_lwb_c`, lambda0, gamma, thetavec, vvec, a, alpha, beta, nu, phi, s1, s2, c1, c2, a1, a2, b1, b2, g1, g2, f1, f2)
}

#' Hazard rate function - HBT
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate
#' @param a Change point
#' @param thetavec Locations
#' @param wvec Weights
#' 
#' @description Hazard rate function for HBT hazard
#' 
#' @export
hazf_hbt_c <- function(tvec, lambda0, a, thetavec, wvec) {
    .Call(`_gamrel_hazf_hbt_c`, tvec, lambda0, a, thetavec, wvec)
}

#' Integrated Hazard rate function - HBT
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate
#' @param a Change point
#' @param thetavec Locations
#' @param wvec Weights
#' 
#' @description Integrated hazard rate function for HBT hazard
#' 
#' @export
chzf_hbt_c <- function(tvec, lambda0, a, thetavec, wvec) {
    .Call(`_gamrel_chzf_hbt_c`, tvec, lambda0, a, thetavec, wvec)
}

#' Hazard and Integrated Hazard rate functions - HBT
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate
#' @param a Change point
#' @param thetavec Locations
#' @param wvec Weights
#' 
#' @description Hazard rate and integrated hazard rate functions generated by 
#' a set of discrete locations and weights and integrated
#' 
#' @export
hazf_chzf_hbt_c <- function(tvec, lambda0, a, thetavec, wvec) {
    .Call(`_gamrel_hazf_chzf_hbt_c`, tvec, lambda0, a, thetavec, wvec)
}

#' Hazard rate function - HCV
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate
#' @param a Change point
#' @param thetavec Locations
#' @param wvec Weights
#' 
#' @description Hazard rate function for HCV hazard
#' 
#' @export
hazf_hcv_c <- function(tvec, lambda0, a, thetavec, wvec) {
    .Call(`_gamrel_hazf_hcv_c`, tvec, lambda0, a, thetavec, wvec)
}

#' Integrated Hazard rate function - HCV
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate
#' @param a Change point
#' @param thetavec Locations
#' @param wvec Weights
#' 
#' @description Integrated hazard rate function for HCV hazard
#' 
#' @export
chzf_hcv_c <- function(tvec, lambda0, a, thetavec, wvec) {
    .Call(`_gamrel_chzf_hcv_c`, tvec, lambda0, a, thetavec, wvec)
}

#' Hazard and Integrated Hazard rate functions - HCV
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate
#' @param a Change point
#' @param thetavec Locations
#' @param wvec Weights
#' 
#' @description Hazard rate and integrated hazard rate functions generated by 
#' a set of discrete locations and weights and integrated
#' 
#' @export
hazf_chzf_hcv_c <- function(tvec, lambda0, a, thetavec, wvec) {
    .Call(`_gamrel_hazf_chzf_hcv_c`, tvec, lambda0, a, thetavec, wvec)
}

#' Hazard rate function - SBT
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate
#' @param thetavec1 DFR Locations
#' @param wvec1 DFR Weights
#' @param thetavec2 IFR Locations
#' @param wvec2 IFR Weights
#' 
#' @description Hazard rate function for SBT hazard
#' 
#' @export
hazf_sbt_c <- function(tvec, lambda0, thetavec1, wvec1, thetavec2, wvec2) {
    .Call(`_gamrel_hazf_sbt_c`, tvec, lambda0, thetavec1, wvec1, thetavec2, wvec2)
}

#' Integrated Hazard rate function - SBT
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate
#' @param thetavec1 DFR Locations
#' @param wvec1 DFR Weights
#' @param thetavec2 IFR Locations
#' @param wvec2 IFR Weights
#' @param lambda0 Offset to be added to the hazard rate
#' 
#' @description Integrated hazard rate function for SBT hazard
#' 
#' @export
chzf_sbt_c <- function(tvec, lambda0, thetavec1, wvec1, thetavec2, wvec2) {
    .Call(`_gamrel_chzf_sbt_c`, tvec, lambda0, thetavec1, wvec1, thetavec2, wvec2)
}

#' Hazard and Integrated Hazard rate functions - SBT
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate
#' @param thetavec1 DFR Locations
#' @param wvec1 DFR Weights
#' @param thetavec2 IFR Locations
#' @param wvec2 IFR Weights
#' 
#' @description Hazard rate and integrated hazard rate functions generated by 
#' a set of discrete locations and weights and integrated
#' 
#' @export
hazf_chzf_sbt_c <- function(tvec, lambda0, thetavec1, wvec1, thetavec2, wvec2) {
    .Call(`_gamrel_hazf_chzf_sbt_c`, tvec, lambda0, thetavec1, wvec1, thetavec2, wvec2)
}

#' Hazard rate function - SCV
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate
#' @param thetavec1 DFR Locations
#' @param wvec1 DFR Weights
#' @param thetavec2 IFR Locations
#' @param wvec2 IFR Weights
#' 
#' @description Hazard rate function for SCV hazard
#' 
#' @export
hazf_scv_c <- function(tvec, lambda0, thetavec1, wvec1, thetavec2, wvec2) {
    .Call(`_gamrel_hazf_scv_c`, tvec, lambda0, thetavec1, wvec1, thetavec2, wvec2)
}

#' Integrated Hazard rate function - SCV
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate
#' @param thetavec1 DFR Locations
#' @param wvec1 DFR Weights
#' @param thetavec2 IFR Locations
#' @param wvec2 IFR Weights
#' @param lambda0 Offset to be added to the hazard rate
#' 
#' @description Integrated hazard rate function for SCV hazard
#' 
#' @export
chzf_scv_c <- function(tvec, lambda0, thetavec1, wvec1, thetavec2, wvec2) {
    .Call(`_gamrel_chzf_scv_c`, tvec, lambda0, thetavec1, wvec1, thetavec2, wvec2)
}

#' Hazard and Integrated Hazard rate functions - SCV
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate
#' @param thetavec1 DFR Locations
#' @param wvec1 DFR Weights
#' @param thetavec2 IFR Locations
#' @param wvec2 IFR Weights
#' 
#' @description Hazard rate and integrated hazard rate functions generated by 
#' a set of discrete locations and weights and integrated
#' 
#' @export
hazf_chzf_scv_c <- function(tvec, lambda0, thetavec1, wvec1, thetavec2, wvec2) {
    .Call(`_gamrel_hazf_chzf_scv_c`, tvec, lambda0, thetavec1, wvec1, thetavec2, wvec2)
}

#' Hazard rate function - MBT
#' 
#' @param tvec Locations at which to evaluate the function
#' @param pival Proportion of the mixture in the DFR component
#' @param lambda0 Offset to be added to the hazard rate
#' @param thetavec1 DFR Locations
#' @param wvec1 DFR Weights
#' @param thetavec2 IFR Locations
#' @param wvec2 IFR Weights
#' 
#' @description Hazard rate function for MBT hazard
#' 
#' @export
hazf_mbt_c <- function(tvec, pival, lambda0, thetavec1, wvec1, thetavec2, wvec2) {
    .Call(`_gamrel_hazf_mbt_c`, tvec, pival, lambda0, thetavec1, wvec1, thetavec2, wvec2)
}

#' Integrated Hazard rate function - MBT
#' 
#' @param tvec Locations at which to evaluate the function
#' @param pival Proportion of the mixture in the DFR component
#' @param lambda0 Offset to be added to the hazard rate
#' @param thetavec1 DFR Locations
#' @param wvec1 DFR Weights
#' @param thetavec2 IFR Locations
#' @param wvec2 IFR Weights
#' @param lambda0 Offset to be added to the hazard rate
#' 
#' @description Integrated hazard rate function for MBT hazard
#' 
#' @export
chzf_mbt_c <- function(tvec, pival, lambda0, thetavec1, wvec1, thetavec2, wvec2) {
    .Call(`_gamrel_chzf_mbt_c`, tvec, pival, lambda0, thetavec1, wvec1, thetavec2, wvec2)
}

#' Hazard and Integrated Hazard rate functions - MBT
#' 
#' @param tvec Locations at which to evaluate the function
#' @param pival Proportion of the mixture in the DFR component
#' @param lambda0 Offset to be added to the hazard rate
#' @param thetavec1 DFR Locations
#' @param wvec1 DFR Weights
#' @param thetavec2 IFR Locations
#' @param wvec2 IFR Weights
#' 
#' @description Hazard rate and integrated hazard rate functions generated by 
#' a set of discrete locations and weights and integrated
#' 
#' @export
hazf_chzf_mbt_c <- function(tvec, pival, lambda0, thetavec1, wvec1, thetavec2, wvec2) {
    .Call(`_gamrel_hazf_chzf_mbt_c`, tvec, pival, lambda0, thetavec1, wvec1, thetavec2, wvec2)
}

#' Hazard rate function - LCV
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to scale the hazard rate
#' @param w0 Offset to be added to the slope of the log hazard rate
#' @param thetavec Locations
#' @param wvec Weights
#' 
#' @description Hazard rate function for LCV hazard
#' 
#' @export
hazf_lcv_c <- function(tvec, lambda0, w0, thetavec, wvec) {
    .Call(`_gamrel_hazf_lcv_c`, tvec, lambda0, w0, thetavec, wvec)
}

#' Integrated Hazard rate function - LCV
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to scale the hazard rate
#' @param w0 Offset to be added to the slope of the log hazard rate
#' @param thetavec Locations
#' @param wvec Weights
#' @param epsilon Size of value close to zero
#' 
#' @description Integrated hazard rate function for LCV hazard
#' 
#' @export
chzf_lcv_c <- function(tvec, lambda0, w0, thetavec, wvec, epsilon) {
    .Call(`_gamrel_chzf_lcv_c`, tvec, lambda0, w0, thetavec, wvec, epsilon)
}

#' Hazard and Integrated Hazard rate functions - LCV
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to scale the hazard rate
#' @param w0 Offset to be added to the slope of the log hazard rate
#' @param thetavec Locations
#' @param wvec Weights
#' @param epsilon Size of value close to zero
#' 
#' @description Hazard rate and integrated hazard rate functions generated by 
#' a set of discrete locations and weights and integrated
#' 
#' @export
hazf_chzf_lcv_c <- function(tvec, lambda0, w0, thetavec, wvec, epsilon) {
    .Call(`_gamrel_hazf_chzf_lcv_c`, tvec, lambda0, w0, thetavec, wvec, epsilon)
}

#' Log prior - LCV
#' 
#' 
#' @param eta eta
#' @param gamma gamma
#' 
#' @description log(prior) for the LCV model - in vector form
#' 
#' @export
logprior_lcv_c <- function(lambda0, w0, gamma, thetavec, vvec, alpha, beta, nu, phi, s1, s2, sigmapw0, a1, a2, b1, b2, g1, g2, f1, f2) {
    .Call(`_gamrel_logprior_lcv_c`, lambda0, w0, gamma, thetavec, vvec, alpha, beta, nu, phi, s1, s2, sigmapw0, a1, a2, b1, b2, g1, g2, f1, f2)
}

#' Hazard rate function - MEW
#' 
#' @param tvec Locations at which to evaluate the function
#' @param alpha alpha
#' @param beta beta
#' @param nu nu
#' @param mu mu 
#' 
#' @description Hazard rate function for MEW hazard
#' 
#' @export
hazf_mew_c <- function(tvec, alpha, beta, mu, nu) {
    .Call(`_gamrel_hazf_mew_c`, tvec, alpha, beta, mu, nu)
}

#' Integrated Hazard rate function - MEW
#' 
#' @param tvec Locations at which to evaluate the function
#' @param alpha alpha
#' @param beta beta
#' @param nu nu
#' @param mu mu 
#' 
#' @description Integrated hazard rate function for MEW hazard
#' 
#' @export
chzf_mew_c <- function(tvec, alpha, beta, mu, nu) {
    .Call(`_gamrel_chzf_mew_c`, tvec, alpha, beta, mu, nu)
}

#' Hazard and Integrated Hazard rate functions - MEW
#' 
#' @param tvec Locations at which to evaluate the function
#' @param alpha alpha
#' @param beta beta
#' @param nu nu
#' @param mu mu 
#' 
#' @description Hazard rate and integrated hazard rate functions generated by 
#' a set of discrete locations and weights and integrated
#' 
#' @export
hazf_chzf_mew_c <- function(tvec, alpha, beta, mu, nu) {
    .Call(`_gamrel_hazf_chzf_mew_c`, tvec, alpha, beta, mu, nu)
}

#' Log prior - MEW
#' 
#' 
#' @param alpha alpha
#' @param beta beta
#' @param mu mu
#' @param nu nu
#' @param a1 a1 Prior for alpha
#' @param a2 a2 Prior for alpha
#' @param b1 b1 Prior for beta
#' @param b2 b2 Prior for beta
#' @param s1 s1 Prior for mu
#' @param s2 s2 Prior for mu
#' @param t1 t1 Prior for nu
#' @param t2 t2 Prior for nu
#' 
#' @description log(prior) for the MEW model - in vector form
#' 
#' @export
logprior_mew_c <- function(alpha, beta, mu, nu, a1, a2, b1, b2, s1, s2, t1, t2) {
    .Call(`_gamrel_logprior_mew_c`, alpha, beta, mu, nu, a1, a2, b1, b2, s1, s2, t1, t2)
}

#' Function to sort an array using shellSort
#'  
#' @export
shellSort_c <- function(x) {
    .Call(`_gamrel_shellSort_c`, x)
}

#' Function to return the sorting order of an array
#'  
#' @export
order_c <- function(x) {
    .Call(`_gamrel_order_c`, x)
}

rcpp_hello_world <- function() {
    .Call(`_gamrel_rcpp_hello_world`)
}

