# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Take the square root of a number
#'
#' @param x A number.
#' @return sqrt(x)
#' @export
csqrt <- function(x) {
    .Call(`_gamrel_csqrt`, x)
}

#' C version of order() - bad performance with duplicates
#' 
#' @export
order1_c <- function(x) {
    .Call(`_gamrel_order1_c`, x)
}

#' C version of mean()
#' 
#' @export
mean_c <- function(x) {
    .Call(`_gamrel_mean_c`, x)
}

#' Hazard rate function - IFR
#' 
#' @param tvec Locations at which to evaluate the function
#' @param thetavec Set of support locations
#' @param wvec Set of associated weights
#' @param lambda0 Offset to be added to the hazard rate
#' 
#' @description Hazard rate function generated by 
#' a set of discrete locations and weights and integrated
#' 
#' @export
lambda_func_ifr_c <- function(tvec, lambda0, thetavec, wvec) {
    .Call(`_gamrel_lambda_func_ifr_c`, tvec, lambda0, thetavec, wvec)
}

#' Hazard rate function - DFR
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate
#' @param thetavec Set of support locations
#' @param wvec Set of associated weights
#' 
#' @description Hazard rate function generated by 
#' a set of discrete locations and weights and integrated
#' 
#' @export
lambda_func_dfr_c <- function(tvec, lambda0, thetavec, wvec) {
    .Call(`_gamrel_lambda_func_dfr_c`, tvec, lambda0, thetavec, wvec)
}

#' Hazard rate function - LWB
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate
#' @param a inflection point
#' @param thetavec Set of support locations
#' @param wvec Set of associated weights
#' 
#' @export
lambda_func_lwb_c <- function(tvec, lambda0, a, thetavec, wvec) {
    .Call(`_gamrel_lambda_func_lwb_c`, tvec, lambda0, a, thetavec, wvec)
}

#' Integrated hazard rate function - IFR version
#' 
#' @param tvec Locations at which to evaluate the function
#' @param thetavec Set of support locations
#' @param wvec Set of associated weights
#' @param lambda0 Offset to be added to the hazard rate (ignored)
#' 
#' @description Hazard rate function generated by 
#' a set of discrete locations and weights and integrated
#' 
#' @export
int_lambda_func_ifr_c <- function(tvec, lambda0, thetavec, wvec) {
    .Call(`_gamrel_int_lambda_func_ifr_c`, tvec, lambda0, thetavec, wvec)
}

#' Integrated hazard rate function - DFR version
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate (ignored)
#' @param thetavec Set of support locations
#' @param wvec Set of associated weights
#' 
#' @description Hazard rate function generated by 
#' a set of discrete locations and weights and integrated
#' 
#' @export
int_lambda_func_dfr_c <- function(tvec, lambda0, thetavec, wvec) {
    .Call(`_gamrel_int_lambda_func_dfr_c`, tvec, lambda0, thetavec, wvec)
}

#' Integrated hazard rate function - LWB version
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate (ignored)
#' @param a inflection point
#' @param thetavec Set of support locations
#' @param wvec Set of associated weights
#' 
#' @description Hazard rate function generated by 
#' a set of discrete locations and weights and integrated
#' 
#' @export
int_lambda_func_lwb_c <- function(tvec, lambda0, a, thetavec, wvec) {
    .Call(`_gamrel_int_lambda_func_lwb_c`, tvec, lambda0, a, thetavec, wvec)
}

#' Integrated hazard rate function - Log Convex version
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 hazard rate scaling
#' @param w0 hazard rate gradient offset
#' @param thetavec Set of support locations
#' @param wvec Set of associated weights
#' 
#' @description Integrated hazard rate function generated by 
#' a set of discrete locations and weights and integrated
#' 
#' @export
int_lambda_func_lcv_c <- function(tvec, lambda0, w0, thetavec, wvec) {
    .Call(`_gamrel_int_lambda_func_lcv_c`, tvec, lambda0, w0, thetavec, wvec)
}

#' Function to sort an array using shellSort
#'  
#' @export
shellSort_c <- function(x) {
    .Call(`_gamrel_shellSort_c`, x)
}

#' Function to return the sorting order of an array
#'  
#' @export
order_c <- function(x) {
    .Call(`_gamrel_order_c`, x)
}

rcpp_hello_world <- function() {
    .Call(`_gamrel_rcpp_hello_world`)
}

