# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Take the square root of a number
#'
#' @param x A number.
#' @return sqrt(x)
#' @export
csqrt <- function(x) {
    .Call(`_gamrel_csqrt`, x)
}

#' Log prior - MEW
NULL

#' C version of order() - bad performance with duplicates
#' 
#' @export
order1_c <- function(x) {
    .Call(`_gamrel_order1_c`, x)
}

#' C version of mean()
#' 
#' @export
mean_c <- function(x) {
    .Call(`_gamrel_mean_c`, x)
}

#' Make DPP beta draws given a set of unscaled stick breaking weights
#' 
#' @export
makev_c <- function(uvec) {
    .Call(`_gamrel_makev_c`, uvec)
}

#' Log prior - IFR/DFR
#' 
#' 
#' @param eta eta
#' @param gamma gamma
#' 
#' @description log(prior) for the IFR and DFR models - in vector form
#' 
#' @export
lprior_ifrdfr_c <- function(eta, gamma, thetavec, vvec, alpha, beta, phi, nu, a1, a2, b1, b2, f1, f2) {
    .Call(`_gamrel_lprior_ifrdfr_c`, eta, gamma, thetavec, vvec, alpha, beta, phi, nu, a1, a2, b1, b2, f1, f2)
}

#' Log prior - LWB
#' 
#' 
#' @param eta eta
#' @param gamma gamma
#' 
#' @description log(prior) for the LWB model - in vector form
#' 
#' @export
lprior_lwb_c <- function(eta, a, gamma, thetavec, vvec, alpha, beta, phi, nu, c1, c2, a1, a2, b1, b2, f1, f2) {
    .Call(`_gamrel_lprior_lwb_c`, eta, a, gamma, thetavec, vvec, alpha, beta, phi, nu, c1, c2, a1, a2, b1, b2, f1, f2)
}

#' Log prior - SBT
#' 
#' 
#' @param eta eta
#' @param gamma gamma
#' 
#' @description log(prior) for the SBT model - in vector form
#' 
#' @export
lprior_sbt_c <- function(eta, gamma1, thetavec1, vvec1, alpha1, beta1, phi1, gamma2, thetavec2, vvec2, alpha2, beta2, phi2, nu, a1, a2, b1, b2, f11, f12, f21, f22) {
    .Call(`_gamrel_lprior_sbt_c`, eta, gamma1, thetavec1, vvec1, alpha1, beta1, phi1, gamma2, thetavec2, vvec2, alpha2, beta2, phi2, nu, a1, a2, b1, b2, f11, f12, f21, f22)
}

#' Log prior - MBT
#' 
#' 
#' @param eta eta
#' @param gamma gamma
#' 
#' @description log(prior) for the MBT model - in vector form
#' 
#' @export
lprior_mbt_c <- function(pival, eta1, gamma1, thetavec1, vvec1, alpha1, beta1, phi1, eta2, gamma2, thetavec2, vvec2, alpha2, beta2, phi2, nu, a1, a2, b1, b2, f11, f21, f12, f22) {
    .Call(`_gamrel_lprior_mbt_c`, pival, eta1, gamma1, thetavec1, vvec1, alpha1, beta1, phi1, eta2, gamma2, thetavec2, vvec2, alpha2, beta2, phi2, nu, a1, a2, b1, b2, f11, f21, f12, f22)
}

#' Log prior - LCV
#' 
#' 
#' @param eta eta
#' @param gamma gamma
#' 
#' @description log(prior) for the LCV model - in vector form
#' 
#' @export
lprior_lcv_c <- function(lambda0, w0, gamma, thetavec, vvec, alpha, beta, phi, s1, s2, sigmap_w0, a1, a2, b1, b2, f1, f2) {
    .Call(`_gamrel_lprior_lcv_c`, lambda0, w0, gamma, thetavec, vvec, alpha, beta, phi, s1, s2, sigmap_w0, a1, a2, b1, b2, f1, f2)
}

lprior_mew_c <- function(lambda, alpha, theta, gamma, s1, s2, a1, a2, t1, t2, g1, g2) {
    .Call(`_gamrel_lprior_mew_c`, lambda, alpha, theta, gamma, s1, s2, a1, a2, t1, t2, g1, g2)
}

#' Hazard rate function - IFR
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate
#' @param thetavec Set of support locations
#' @param wvec Set of associated weights
#' 
#' @description Hazard rate function generated by 
#' a set of discrete locations and weights and integrated
#' 
#' @export
lambda_func_ifr_c <- function(tvec, lambda0, thetavec, wvec) {
    .Call(`_gamrel_lambda_func_ifr_c`, tvec, lambda0, thetavec, wvec)
}

#' Hazard rate function - DFR
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate
#' @param thetavec Set of support locations
#' @param wvec Set of associated weights
#' 
#' @description Hazard rate function generated by 
#' a set of discrete locations and weights and integrated
#' 
#' @export
lambda_func_dfr_c <- function(tvec, lambda0, thetavec, wvec) {
    .Call(`_gamrel_lambda_func_dfr_c`, tvec, lambda0, thetavec, wvec)
}

#' Hazard rate function - LWB
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate
#' @param a inflection point
#' @param thetavec Set of support locations
#' @param wvec Set of associated weights
#' 
#' @export
lambda_func_lwb_c <- function(tvec, lambda0, a, thetavec, wvec) {
    .Call(`_gamrel_lambda_func_lwb_c`, tvec, lambda0, a, thetavec, wvec)
}

#' Hazard rate function - LCV
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 scaling
#' @param Offset to be added to the log hazard rate derivatice
#' @param thetavec Set of support locations
#' @param wvec Set of associated weights
#' 
#' @description Hazard rate function generated by 
#' a set of discrete locations and weights and integrated
#' 
#' @export
lambda_func_lcv_c <- function(tvec, lambda0, w0, thetavec, wvec) {
    .Call(`_gamrel_lambda_func_lcv_c`, tvec, lambda0, w0, thetavec, wvec)
}

#' Integrated hazard rate function - IFR version
#' 
#' @param tvec Locations at which to evaluate the function
#' @param thetavec Set of support locations
#' @param wvec Set of associated weights
#' @param lambda0 Offset to be added to the hazard rate (ignored)
#' 
#' @description Hazard rate function generated by 
#' a set of discrete locations and weights and integrated
#' 
#' @export
int_lambda_func_ifr_c <- function(tvec, lambda0, thetavec, wvec) {
    .Call(`_gamrel_int_lambda_func_ifr_c`, tvec, lambda0, thetavec, wvec)
}

#' Integrated hazard rate function - DFR version
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate (ignored)
#' @param thetavec Set of support locations
#' @param wvec Set of associated weights
#' 
#' @description Hazard rate function generated by 
#' a set of discrete locations and weights and integrated
#' 
#' @export
int_lambda_func_dfr_c <- function(tvec, lambda0, thetavec, wvec) {
    .Call(`_gamrel_int_lambda_func_dfr_c`, tvec, lambda0, thetavec, wvec)
}

#' Integrated hazard rate function - LWB version
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate (ignored)
#' @param a inflection point
#' @param thetavec Set of support locations
#' @param wvec Set of associated weights
#' 
#' @description Hazard rate function generated by 
#' a set of discrete locations and weights and integrated
#' 
#' @export
int_lambda_func_lwb_c <- function(tvec, lambda0, a, thetavec, wvec) {
    .Call(`_gamrel_int_lambda_func_lwb_c`, tvec, lambda0, a, thetavec, wvec)
}

#' Integrated hazard rate function - Log Convex version
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 hazard rate scaling
#' @param w0 hazard rate gradient offset
#' @param thetavec Set of support locations
#' @param wvec Set of associated weights
#' 
#' @description Integrated hazard rate function generated by 
#' a set of discrete locations and weights and integrated
#' 
#' @export
int_lambda_func_lcv_c <- function(tvec, lambda0, w0, thetavec, wvec, epsilon) {
    .Call(`_gamrel_int_lambda_func_lcv_c`, tvec, lambda0, w0, thetavec, wvec, epsilon)
}

#' Hazard and Integrated Hazard rate functions - IFR
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate
#' @param thetavec Set of support locations
#' @param wvec Set of associated weights
#' 
#' @description Hazard rate and integrated hazard rate functions generated by 
#' a set of discrete locations and weights and integrated
#' 
#' @export
both_lambda_func_ifr_c <- function(tvec, lambda0, thetavec, wvec) {
    .Call(`_gamrel_both_lambda_func_ifr_c`, tvec, lambda0, thetavec, wvec)
}

#' Hazard rate and integrated hazard rate functions - DFR
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate
#' @param thetavec Set of support locations
#' @param wvec Set of associated weights
#' 
#' @description Hazard rate function generated by 
#' a set of discrete locations and weights and integrated
#' 
#' @export
both_lambda_func_dfr_c <- function(tvec, lambda0, thetavec, wvec) {
    .Call(`_gamrel_both_lambda_func_dfr_c`, tvec, lambda0, thetavec, wvec)
}

#' Hazard and integrated hazard rate functions - LWB
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 Offset to be added to the hazard rate
#' @param a inflection point
#' @param thetavec Set of support locations
#' @param wvec Set of associated weights
#' 
#' @export
both_lambda_func_lwb_c <- function(tvec, lambda0, a, thetavec, wvec) {
    .Call(`_gamrel_both_lambda_func_lwb_c`, tvec, lambda0, a, thetavec, wvec)
}

#' Hazard and integrated hazard rate functions - LCV
#' 
#' @param tvec Locations at which to evaluate the function
#' @param lambda0 scaling
#' @param Offset to be added to the log hazard rate derivatice
#' @param thetavec Set of support locations
#' @param wvec Set of associated weights
#' 
#' @description Hazard rate function generated by 
#' a set of discrete locations and weights and integrated
#' 
#' @export
both_lambda_func_lcv_c <- function(tvec, lambda0, w0, thetavec, wvec, epsilon) {
    .Call(`_gamrel_both_lambda_func_lcv_c`, tvec, lambda0, w0, thetavec, wvec, epsilon)
}

#' Function to sort an array using shellSort
#'  
#' @export
shellSort_c <- function(x) {
    .Call(`_gamrel_shellSort_c`, x)
}

#' Function to return the sorting order of an array
#'  
#' @export
order_c <- function(x) {
    .Call(`_gamrel_order_c`, x)
}

rcpp_hello_world <- function() {
    .Call(`_gamrel_rcpp_hello_world`)
}

